name: Monitor Tokens

on:
  schedule:
    - cron: "0 * * * *"   # cada hora
  workflow_dispatch:       # para lanzarlo manualmente

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1. Descargar artefactos previos (tokens JSON)
      - name: Descargar tokens guardados
        uses: actions/download-artifact@v4
        with:
          name: solana-data
          path: .
        continue-on-error: true

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Instalar dependencias
      - name: Instalar dependencias
        run: pip install -r requirements.txt

      # 4. Ejecutar script
      - name: Ejecutar monitor
        env:
          API_KEY_COINGECKO: ${{ secrets.API_KEY_COINGECKO }}
          API_KEY_GEMINI: ${{ secrets.API_KEY_GEMINI }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TO_EMAILS: ${{ secrets.TO_EMAILS }}
        run: python monitor.py

      # 5. Subir tokens actualizados como artefacto
      - name: Subir tokens actualizados
        uses: actions/upload-artifact@v4
        with:
          name: solana-data
          path: |
            solana_tokens.json
            processed_tokens.json
